AWSTemplateFormatVersion: "2010-09-09"
Description: "Instances to host the application."
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: "makatas"
      ImageId: "ami-088ff0e3bde7b3fdf"
      UserData: !Base64 |
        #!/bin/bash
        yum -y update

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access via port 22"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: "203.87.124.146/32"
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
