AWSTemplateFormatVersion: "2010-09-09"
Description: "Set up a Jenkins server."
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: "makatas"
      ImageId: "ami-020d764f9372da231"
      UserData: !Base64 |
        #!/bin/bash
        yum -y update
        yum install java-1.8.0-openjdk
        #update-alternatives --config java
        sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
        sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
        sudo yum install jenkins -y
        sudo service jenkins start
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access via port 22"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: "203.87.124.146/32"
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
